# Generated by Django 2.2.3 on 2019-08-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='boards',
            new_name='board',
        ),
    ]
